spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/farm2home?currentSchema=delivery
    username: ${DB_USERNAME:farm2home}
    password: ${DB_PASSWORD:farm2home@123}
  flyway:
    schemas: delivery
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:password@discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.farm2home: INFO
