-- Farm2Home Milk — PostgreSQL schema initialization
-- Each microservice owns its own schema

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS subscription;
CREATE SCHEMA IF NOT EXISTS "order";
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS delivery;
CREATE SCHEMA IF NOT EXISTS farm;
CREATE SCHEMA IF NOT EXISTS production;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS notification;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA customer TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA subscription TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "order" TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payment TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA delivery TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA farm TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA production TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA inventory TO farm2home;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA notification TO farm2home;
