spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/farm2home?currentSchema=auth
    username: ${DB_USERNAME:farm2home}
    password: ${DB_PASSWORD:farm2home@123}
  flyway:
    schemas: auth

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka%40secret@discovery-service:8761/eureka

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.farm2home: INFO
