-- Upgrades the 3 existing plain-text EMAIL templates to basic HTML, and adds 2 new ones
-- (OTP, delivery delay). All share the same minimal inline-styled layout - no templating
-- engine, no partials, just full standalone HTML per row (matches this table's existing
-- "one row = one renderable message" design).

UPDATE notification.notification_templates
SET subject = 'Welcome to Farm2Home Milk',
    body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Welcome, {{customer_name}}!</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Thank you for joining Farm2Home Milk. Your account has been created successfully, and fresh, farm-sourced milk is now just an order away.</p><p style="font-size:15px;line-height:1.5;margin:0;">Set up a subscription or place a one-time order any time from the app.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'CUSTOMER_CREATED_EMAIL';

UPDATE notification.notification_templates
SET subject = 'Order Confirmed - Farm2Home Milk',
    body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Order Confirmed</p><p style="font-size:15px;line-height:1.5;margin:0 0 20px;">Dear {{customer_name}}, your order has been placed successfully. Here are the details:</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;"><tr><td style="border-bottom:1px solid #eeeeee;color:#777777;font-size:13px;">Order Number</td><td style="border-bottom:1px solid #eeeeee;text-align:right;font-weight:bold;font-size:14px;">{{order_number}}</td></tr><tr><td style="color:#777777;font-size:13px;">Amount</td><td style="text-align:right;font-weight:bold;font-size:14px;">Rs {{amount}}</td></tr></table><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">We are preparing your order for delivery and will notify you once it is on its way.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'ORDER_CREATED_EMAIL';

UPDATE notification.notification_templates
SET subject = 'Payment Receipt - Farm2Home Milk',
    body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Payment Received</p><p style="font-size:15px;line-height:1.5;margin:0 0 20px;">Dear {{customer_name}}, we have received your payment. This email is your receipt.</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;background-color:#f9f9f9;border-radius:6px;"><tr><td style="padding:12px;color:#777777;font-size:13px;">Order Number</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;">{{order_number}}</td></tr><tr><td style="padding:12px;color:#777777;font-size:13px;border-top:1px solid #eeeeee;">Reference</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;border-top:1px solid #eeeeee;">{{reference}}</td></tr><tr><td style="padding:12px;color:#777777;font-size:13px;border-top:1px solid #eeeeee;">Amount Paid</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:16px;color:#2e7d32;border-top:1px solid #eeeeee;">Rs {{amount}}</td></tr></table><p style="font-size:13px;color:#777777;margin:0;">Keep this email for your records.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'PAYMENT_SUCCESS_EMAIL';

INSERT INTO notification.notification_templates (template_code, channel, subject, body) VALUES
('OTP_EMAIL', 'EMAIL', 'Your Farm2Home Milk verification code',
 '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:16px;margin:0 0 16px;">Hello,</p><p style="font-size:15px;line-height:1.5;margin:0 0 24px;">Use the code below to verify your Farm2Home Milk account. This code expires in 5 minutes.</p><div style="text-align:center;margin:0 0 24px;"><span style="display:inline-block;font-size:32px;font-weight:bold;letter-spacing:8px;color:#2e7d32;background-color:#f1f8f2;padding:16px 24px;border-radius:6px;">{{otp}}</span></div><p style="font-size:13px;color:#777777;margin:0;">If you did not request this code, you can safely ignore this email.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'),
('DELIVERY_DELAYED_EMAIL', 'EMAIL', 'Your delivery has been delayed - Farm2Home Milk',
 '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#e65100;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Delivery Delayed</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">We are sorry to let you know that your delivery with {{partner_name}} is running behind schedule.</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;background-color:#fff8f1;border-radius:6px;"><tr><td style="padding:12px;color:#777777;font-size:13px;">Reason</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;">{{reason}}</td></tr></table><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">We apologize for the inconvenience and are working to get your order to you as soon as possible.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>');
