spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/farm2home?currentSchema=subscription
    username: ${DB_USERNAME:farm2home}
    password: ${DB_PASSWORD:farm2home@123}
  flyway:
    schemas: subscription
    create-schemas: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eurekaSecret@discovery-service:8761/eureka

configserver:
  health:
    url: http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env

logging:
  level:
    com.farm2home: INFO
