spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/farm2home?currentSchema=subscription
    username: ${DB_USERNAME:farm2home}
    password: ${DB_PASSWORD:farm2home@123}
  flyway:
    schemas: subscription
    create-schemas: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@secret@discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.farm2home: INFO
