import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, TextField, Tooltip } from '@mui/material'
import { Add, ArrowBack, Delete, Edit, Refresh } from '@mui/icons-material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useSnackbar } from 'notistack'
import { DataGrid, type GridColDef } from '@mui/x-data-grid'
import { ConfirmDialog } from '../../components/common/ConfirmDialog'
import { PageHeader } from '../../components/common/PageHeader'
import { indiaLocationService } from '../../services/indiaLocationService'
import { locationMasterService, type LocationKind, type LocationMasterItem, type LocationMasterPayload } from '../../services/locationMasterService'

export function LocationMasterListPage({ type }: { type: LocationKind }) {
  const navigate = useNavigate(), qc = useQueryClient(), { enqueueSnackbar } = useSnackbar()
  const title = type[0].toUpperCase() + type.slice(1)
  const [search, setSearch] = useState(''), [stateId, setStateId] = useState(''), [districtId, setDistrictId] = useState('')
  const [editing, setEditing] = useState<LocationMasterItem | null>(null), [formOpen, setFormOpen] = useState(false), [deleting, setDeleting] = useState<LocationMasterItem | null>(null)
  const filters = { search: search || undefined, stateId: stateId || undefined, districtId: districtId || undefined }
  const query = useQuery({ queryKey: ['location-master', type, filters], queryFn: () => locationMasterService.list(type, filters) })
  const states = useQuery({ queryKey: ['location-states'], queryFn: indiaLocationService.getStates, enabled: type !== 'states' })
  const districts = useQuery({ queryKey: ['location-districts', stateId], queryFn: () => indiaLocationService.getDistricts(stateId), enabled: type === 'cities' && !!stateId })
  const rows = query.data?.data.data ?? []
  const save = useMutation({ mutationFn: ({ id, values }: { id?: string; values: LocationMasterPayload }) => id ? locationMasterService.update(type, id, values) : locationMasterService.create(type, values), onSuccess: () => { enqueueSnackbar(`${title.slice(0, -1)} saved`, { variant: 'success' }); setFormOpen(false); qc.invalidateQueries({ queryKey: ['location-master'] }); qc.invalidateQueries({ queryKey: ['location-'] }) }, onError: (e: any) => enqueueSnackbar(e.response?.data?.message ?? 'Could not save the location.', { variant: 'error' }) })
  const remove = useMutation({ mutationFn: (id: string) => locationMasterService.delete(type, id), onSuccess: () => { enqueueSnackbar(`${title.slice(0, -1)} deleted`, { variant: 'success' }); setDeleting(null); qc.invalidateQueries({ queryKey: ['location-master'] }) }, onError: (e: any) => { setDeleting(null); enqueueSnackbar(e.response?.data?.message ?? 'Could not delete the location.', { variant: 'error' }) } })
  const columns = useMemo<GridColDef<LocationMasterItem>[]>(() => [{ field: 'name', headerName: 'Name', flex: 1, minWidth: 180 }, ...(type !== 'cities' ? [{ field: 'code', headerName: 'Code', width: 120 }] : []), ...(type !== 'states' ? [{ field: type === 'districts' ? 'stateName' : 'districtName', headerName: type === 'districts' ? 'State' : 'District', flex: 1, minWidth: 150 }] : []), { field: 'active', headerName: 'Status', width: 110, renderCell: ({ value }) => <Chip size="small" label={value ? 'Active' : 'Inactive'} color={value ? 'success' : 'default'} /> }, { field: 'actions', headerName: '', width: 100, sortable: false, renderCell: ({ row }) => <><IconButton size="small" onClick={() => { setEditing(row); setFormOpen(true) }}><Edit fontSize="small" /></IconButton><IconButton color="error" size="small" onClick={() => setDeleting(row)}><Delete fontSize="small" /></IconButton></> }], [type])
  const stateRows = states.data?.data.data ?? [], districtRows = districts.data?.data.data ?? []
  return <Box><Button size="small" startIcon={<ArrowBack />} onClick={() => navigate('/settings/location-master')}>Location Master</Button><PageHeader title={`${title} Management`} subtitle={`Search and maintain ${title.toLowerCase()} used in customer addresses.`} action={{ label: `Add ${title.slice(0, -1)}`, icon: <Add />, onClick: () => { setEditing(null); setFormOpen(true) } }} />
    <Stack direction={{ xs: 'column', md: 'row' }} spacing={1.5} mb={2}><TextField size="small" label="Search" value={search} onChange={(e) => setSearch(e.target.value)} />{type !== 'states' && <TextField select size="small" label="State" value={stateId} onChange={(e) => { setStateId(e.target.value); setDistrictId('') }} sx={{ minWidth: 190 }}><MenuItem value="">All states</MenuItem>{stateRows.map((s) => <MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</TextField>}{type === 'cities' && <TextField select size="small" label="District" value={districtId} onChange={(e) => setDistrictId(e.target.value)} disabled={!stateId} sx={{ minWidth: 190 }}><MenuItem value="">All districts</MenuItem>{districtRows.map((d) => <MenuItem key={d.id} value={d.id}>{d.name}</MenuItem>)}</TextField>}<Tooltip title="Refresh"><IconButton onClick={() => query.refetch()}><Refresh /></IconButton></Tooltip></Stack>
    <Paper variant="outlined" sx={{ borderRadius: 2 }}><DataGrid autoHeight rows={rows} columns={columns} loading={query.isLoading || query.isFetching} disableRowSelectionOnClick pageSizeOptions={[25]} initialState={{ pagination: { paginationModel: { pageSize: 25 } } }} /></Paper>
    <LocationDialog open={formOpen} type={type} item={editing} states={stateRows} districts={districtRows} defaultStateId={stateId} onClose={() => setFormOpen(false)} onSave={(values) => save.mutate({ id: editing?.id, values })} saving={save.isPending} />
    <ConfirmDialog open={!!deleting} title={`Delete ${title.slice(0, -1)}?`} message={`"${deleting?.name}" will be permanently removed. Dependent active locations prevent deletion.`} destructive confirmLabel="Delete" loading={remove.isPending} onClose={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id)} />
  </Box>
}

function LocationDialog({ open, type, item, states, districts, defaultStateId, onClose, onSave, saving }: { open: boolean; type: LocationKind; item: LocationMasterItem | null; states: any[]; districts: any[]; defaultStateId: string; onClose: () => void; onSave: (v: LocationMasterPayload) => void; saving: boolean }) {
  const [name, setName] = useState(''), [code, setCode] = useState(''), [stateId, setStateId] = useState(''), [districtId, setDistrictId] = useState(''), [active, setActive] = useState(true)
  const dialogDistricts = useQuery({ queryKey: ['location-master-dialog-districts', stateId], queryFn: () => indiaLocationService.getDistricts(stateId), enabled: type === 'cities' && !!stateId })
  const availableDistricts = type === 'cities' ? (dialogDistricts.data?.data.data ?? districts) : districts
  const initialize = () => { setName(item?.name ?? ''); setCode(item?.code ?? ''); setStateId(item?.stateId ?? defaultStateId); setDistrictId(item?.districtId ?? ''); setActive(item?.active ?? true) }
  return <Dialog open={open} onClose={onClose} onTransitionEnter={initialize} fullWidth maxWidth="xs"><DialogTitle>{item ? 'Edit' : 'Add'} {type.slice(0, -1)}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{type !== 'states' && <TextField select label="State" value={stateId} onChange={(e) => { setStateId(e.target.value); setDistrictId('') }} required>{states.map((s) => <MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</TextField>}{type === 'cities' && <TextField select label="District" value={districtId} onChange={(e) => setDistrictId(e.target.value)} required disabled={!stateId || dialogDistricts.isLoading}>{availableDistricts.map((d) => <MenuItem key={d.id} value={d.id}>{d.name}</MenuItem>)}</TextField>}<TextField label="Name" value={name} required onChange={(e) => setName(e.target.value)} />{type !== 'cities' && <TextField label="Code" value={code} required onChange={(e) => setCode(e.target.value.toUpperCase())} /> }<TextField select label="Status" value={active ? 'true' : 'false'} onChange={(e) => setActive(e.target.value === 'true')}><MenuItem value="true">Active</MenuItem><MenuItem value="false">Inactive</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!name.trim() || (type !== 'cities' && !code.trim()) || (type !== 'states' && !stateId) || (type === 'cities' && !districtId) || saving} onClick={() => onSave({ name: name.trim(), code: code.trim() || undefined, stateId: stateId || undefined, districtId: districtId || undefined, active })}>Save</Button></DialogActions></Dialog>
}
