spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eurekaSecret@discovery-service:8761/eureka/
