server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  security:
    user:
      name: ${CONFIG_USERNAME:configuser}
      password: ${CONFIG_PASSWORD:config@secret}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@secret@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
