-- ============================================================
-- Upgrades every remaining plain-text EMAIL template to the same branded HTML layout V3
-- established for CUSTOMER_CREATED/ORDER_CREATED/PAYMENT_SUCCESS/OTP/DELIVERY_DELAYED - these 9
-- (added later, in V6/V8) were left as bare text, so the notification center/inbox rendered them
-- inconsistently next to the HTML ones. Same structure throughout: green (#2e7d32) header for a
-- neutral/positive update, amber (#e65100) for one that needs the customer's attention (failure/
-- cancellation), matching V3's own DELIVERY_DELAYED precedent. Only placeholders already
-- supported by NotificationServiceImpl.buildPayload() are used - no new ones introduced.
-- ============================================================

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#e65100;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Payment Failed</p><p style="font-size:15px;line-height:1.5;margin:0 0 20px;">Dear {{customer_name}}, we could not process your payment for order #{{order_number}}.</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;background-color:#fff8f1;border-radius:6px;"><tr><td style="padding:12px;color:#777777;font-size:13px;">Order Number</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;">{{order_number}}</td></tr><tr><td style="padding:12px;color:#777777;font-size:13px;border-top:1px solid #f3e0d0;">Reference</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;border-top:1px solid #f3e0d0;">{{reference}}</td></tr><tr><td style="padding:12px;color:#777777;font-size:13px;border-top:1px solid #f3e0d0;">Amount</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;border-top:1px solid #f3e0d0;">Rs {{amount}}</td></tr></table><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">Please try again from the app, or use a different payment method.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'PAYMENT_FAILED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Subscription Started</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Dear {{customer_name}}, your subscription for {{quantity}}L {{milk_type}} milk is now active.</p><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">You will receive a notification before each delivery. Manage your subscription any time from the app.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'SUBSCRIPTION_CREATED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#e65100;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Subscription Paused</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Dear {{customer_name}}, your {{quantity}}L {{milk_type}} subscription has been paused. No deliveries will be scheduled until you resume it.</p><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">You can resume your subscription any time from the app.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'SUBSCRIPTION_PAUSED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Subscription Resumed</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Dear {{customer_name}}, your {{quantity}}L {{milk_type}} subscription is active again. Deliveries will resume on your regular schedule.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'SUBSCRIPTION_RESUMED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#e65100;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Subscription Cancelled</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Dear {{customer_name}}, your {{quantity}}L {{milk_type}} subscription has been cancelled. No further deliveries will be scheduled.</p><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">We would love to have you back - you can start a new subscription any time from the app.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'SUBSCRIPTION_CANCELLED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Out for Delivery</p><p style="font-size:15px;line-height:1.5;margin:0 0 20px;">Dear {{customer_name}}, your order #{{order_number}} is out for delivery with {{partner_name}}.</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;background-color:#f1f8f2;border-radius:6px;"><tr><td style="padding:12px;color:#777777;font-size:13px;">Expected Delivery</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;">{{expected_time}}</td></tr></table><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">You will be notified as soon as your order is delivered.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'DELIVERY_OUT_FOR_DELIVERY_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Your Order is on the Way</p><p style="font-size:15px;line-height:1.5;margin:0 0 20px;">Dear {{customer_name}}, your order #{{order_number}} has been assigned to {{partner_name}}.</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;background-color:#f1f8f2;border-radius:6px;"><tr><td style="padding:12px;color:#777777;font-size:13px;">Expected Delivery</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;">{{expected_time}}</td></tr></table></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'DELIVERY_ASSIGNED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#2e7d32;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Order Delivered</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Dear {{customer_name}}, your order #{{order_number}} has been delivered. Thank you for choosing Farm2Home Milk!</p><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">We hope you enjoy your fresh, farm-sourced milk.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'DELIVERY_COMPLETED_EMAIL';

UPDATE notification.notification_templates
SET body = '<!DOCTYPE html><html><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:24px 0;"><tr><td align="center"><table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background-color:#e65100;padding:20px 24px;"><span style="color:#ffffff;font-size:20px;font-weight:bold;">Farm2Home Milk</span></td></tr><tr><td style="padding:32px 24px;color:#333333;"><p style="font-size:18px;margin:0 0 16px;">Delivery Unsuccessful</p><p style="font-size:15px;line-height:1.5;margin:0 0 16px;">Dear {{customer_name}}, we were unable to deliver your order #{{order_number}}.</p><table role="presentation" width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;margin:0 0 20px;background-color:#fff8f1;border-radius:6px;"><tr><td style="padding:12px;color:#777777;font-size:13px;">Reason</td><td style="padding:12px;text-align:right;font-weight:bold;font-size:14px;">{{reason}}</td></tr></table><p style="font-size:14px;line-height:1.5;margin:0;color:#555555;">Our team will reach out shortly to reschedule your delivery.</p></td></tr><tr><td style="padding:16px 24px;background-color:#fafafa;text-align:center;"><span style="font-size:12px;color:#999999;">This is an automated message from Farm2Home Milk. Please do not reply.</span></td></tr></table></td></tr></table></body></html>'
WHERE template_code = 'DELIVERY_FAILED_EMAIL';
